[pytest]
pythonpath = .
markers =
    unit: small unit tests
    integration: larger tests to test feature integration
    e2e: full system end to end test
    network: marks tests that require network/internet access